safe: true
markdown: kramdown
highlighter: rouge
permalink: /:title.html
relative_permalinks: false

default_theme: ribbon
default_width: 792
default_lang: fr
default_body_class: list

author:
    name: Gauthier POGAM--LE MONTAGNER
    # url:  http://example.com/
    company:
        name: Epitech
        # url:  http://example.com/

fork_url: https://github.com/shower/shower
progress: true
line_numbers: true
